// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnalystService.proto

package it.maurosaladino.sdp.Proto;

public final class AnalystServiceOuterClass {
  private AnalystServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.maurosaladino.sdp.Proto.PushNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
     * @return The type.
     */
    it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type getType();
  }
  /**
   * Protobuf type {@code it.maurosaladino.sdp.Proto.PushNotification}
   */
  public static final class PushNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.maurosaladino.sdp.Proto.PushNotification)
      PushNotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushNotification.newBuilder() to construct.
    private PushNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushNotification() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PushNotification();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PushNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.class, it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Builder.class);
    }

    /**
     * Protobuf enum {@code it.maurosaladino.sdp.Proto.PushNotification.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW_STATISTIC = 0;</code>
       */
      NEW_STATISTIC(0),
      /**
       * <code>NEW_NODE = 1;</code>
       */
      NEW_NODE(1),
      /**
       * <code>EXIT_NODE = 2;</code>
       */
      EXIT_NODE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NEW_STATISTIC = 0;</code>
       */
      public static final int NEW_STATISTIC_VALUE = 0;
      /**
       * <code>NEW_NODE = 1;</code>
       */
      public static final int NEW_NODE_VALUE = 1;
      /**
       * <code>EXIT_NODE = 2;</code>
       */
      public static final int EXIT_NODE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return NEW_STATISTIC;
          case 1: return NEW_NODE;
          case 2: return EXIT_NODE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:it.maurosaladino.sdp.Proto.PushNotification.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type getType() {
      @SuppressWarnings("deprecation")
      it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type result = it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.valueOf(type_);
      return result == null ? it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.NEW_STATISTIC.getNumber()) {
        output.writeEnum(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.NEW_STATISTIC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification)) {
        return super.equals(obj);
      }
      it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification other = (it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification) obj;

      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.maurosaladino.sdp.Proto.PushNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.maurosaladino.sdp.Proto.PushNotification)
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.class, it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Builder.class);
      }

      // Construct using it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification getDefaultInstanceForType() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.getDefaultInstance();
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification build() {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification buildPartial() {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification result = new it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification) {
          return mergeFrom((it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification other) {
        if (other == it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type getType() {
        @SuppressWarnings("deprecation")
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type result = it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.valueOf(type_);
        return result == null ? it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushNotification.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.maurosaladino.sdp.Proto.PushNotification)
    }

    // @@protoc_insertion_point(class_scope:it.maurosaladino.sdp.Proto.PushNotification)
    private static final it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification();
    }

    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushNotification>
        PARSER = new com.google.protobuf.AbstractParser<PushNotification>() {
      @java.lang.Override
      public PushNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushNotification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PushResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.maurosaladino.sdp.Proto.PushResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
     * @return The status.
     */
    it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status getStatus();
  }
  /**
   * Protobuf type {@code it.maurosaladino.sdp.Proto.PushResponse}
   */
  public static final class PushResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.maurosaladino.sdp.Proto.PushResponse)
      PushResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PushResponse.newBuilder() to construct.
    private PushResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushResponse() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PushResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PushResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.class, it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code it.maurosaladino.sdp.Proto.PushResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return OK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:it.maurosaladino.sdp.Proto.PushResponse.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status result = it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.valueOf(status_);
      return result == null ? it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.OK.getNumber()) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse)) {
        return super.equals(obj);
      }
      it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse other = (it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse) obj;

      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.maurosaladino.sdp.Proto.PushResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.maurosaladino.sdp.Proto.PushResponse)
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.class, it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Builder.class);
      }

      // Construct using it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse getDefaultInstanceForType() {
        return it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.getDefaultInstance();
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse build() {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse buildPartial() {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse result = new it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse) {
          return mergeFrom((it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse other) {
        if (other == it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status getStatus() {
        @SuppressWarnings("deprecation")
        it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status result = it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.valueOf(status_);
        return result == null ? it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.PushResponse.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.maurosaladino.sdp.Proto.PushResponse)
    }

    // @@protoc_insertion_point(class_scope:it.maurosaladino.sdp.Proto.PushResponse)
    private static final it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse();
    }

    public static it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushResponse>
        PARSER = new com.google.protobuf.AbstractParser<PushResponse>() {
      @java.lang.Override
      public PushResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.maurosaladino.sdp.Proto.AnalystServiceOuterClass.PushResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_maurosaladino_sdp_Proto_PushNotification_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_maurosaladino_sdp_Proto_PushResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AnalystService.proto\022\032it.maurosaladino" +
      ".sdp.Proto\"\213\001\n\020PushNotification\022?\n\004type\030" +
      "\001 \001(\01621.it.maurosaladino.sdp.Proto.PushN" +
      "otification.Type\"6\n\004Type\022\021\n\rNEW_STATISTI" +
      "C\020\000\022\014\n\010NEW_NODE\020\001\022\r\n\tEXIT_NODE\020\002\"a\n\014Push" +
      "Response\022?\n\006status\030\001 \001(\0162/.it.maurosalad" +
      "ino.sdp.Proto.PushResponse.Status\"\020\n\006Sta" +
      "tus\022\006\n\002OK\020\0002t\n\016AnalystService\022b\n\010sendPus" +
      "h\022,.it.maurosaladino.sdp.Proto.PushNotif" +
      "ication\032(.it.maurosaladino.sdp.Proto.Pus" +
      "hResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_maurosaladino_sdp_Proto_PushNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_maurosaladino_sdp_Proto_PushNotification_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_it_maurosaladino_sdp_Proto_PushResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_maurosaladino_sdp_Proto_PushResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
