// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: P2PService.proto

package it.maurosaladino.sdp.Proto;

public final class P2PServiceOuterClass {
  private P2PServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotifyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.maurosaladino.sdp.Proto.NotifyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 listeningPort = 3;</code>
     * @return The listeningPort.
     */
    int getListeningPort();
  }
  /**
   * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyRequest}
   */
  public static final class NotifyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.maurosaladino.sdp.Proto.NotifyRequest)
      NotifyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NotifyRequest.newBuilder() to construct.
    private NotifyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotifyRequest() {
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NotifyRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 24: {

              listeningPort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LISTENINGPORT_FIELD_NUMBER = 3;
    private int listeningPort_;
    /**
     * <code>int32 listeningPort = 3;</code>
     * @return The listeningPort.
     */
    @java.lang.Override
    public int getListeningPort() {
      return listeningPort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (listeningPort_ != 0) {
        output.writeInt32(3, listeningPort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (listeningPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, listeningPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest)) {
        return super.equals(obj);
      }
      it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest other = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getListeningPort()
          != other.getListeningPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + LISTENINGPORT_FIELD_NUMBER;
      hash = (53 * hash) + getListeningPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.maurosaladino.sdp.Proto.NotifyRequest)
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.Builder.class);
      }

      // Construct using it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        ip_ = "";

        listeningPort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest getDefaultInstanceForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest build() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest buildPartial() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest result = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest(this);
        result.id_ = id_;
        result.ip_ = ip_;
        result.listeningPort_ = listeningPort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest) {
          return mergeFrom((it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest other) {
        if (other == it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getListeningPort() != 0) {
          setListeningPort(other.getListeningPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int listeningPort_ ;
      /**
       * <code>int32 listeningPort = 3;</code>
       * @return The listeningPort.
       */
      @java.lang.Override
      public int getListeningPort() {
        return listeningPort_;
      }
      /**
       * <code>int32 listeningPort = 3;</code>
       * @param value The listeningPort to set.
       * @return This builder for chaining.
       */
      public Builder setListeningPort(int value) {
        
        listeningPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 listeningPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearListeningPort() {
        
        listeningPort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.maurosaladino.sdp.Proto.NotifyRequest)
    }

    // @@protoc_insertion_point(class_scope:it.maurosaladino.sdp.Proto.NotifyRequest)
    private static final it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest();
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyRequest>
        PARSER = new com.google.protobuf.AbstractParser<NotifyRequest>() {
      @java.lang.Override
      public NotifyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotifyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NotifyRequestDeleteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.maurosaladino.sdp.Proto.NotifyRequestDelete)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id_delete = 1;</code>
     * @return The idDelete.
     */
    int getIdDelete();

    /**
     * <code>int32 id_add = 2;</code>
     * @return The idAdd.
     */
    int getIdAdd();

    /**
     * <code>string ip_add = 3;</code>
     * @return The ipAdd.
     */
    java.lang.String getIpAdd();
    /**
     * <code>string ip_add = 3;</code>
     * @return The bytes for ipAdd.
     */
    com.google.protobuf.ByteString
        getIpAddBytes();

    /**
     * <code>int32 listeningPort_add = 4;</code>
     * @return The listeningPortAdd.
     */
    int getListeningPortAdd();
  }
  /**
   * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyRequestDelete}
   */
  public static final class NotifyRequestDelete extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.maurosaladino.sdp.Proto.NotifyRequestDelete)
      NotifyRequestDeleteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NotifyRequestDelete.newBuilder() to construct.
    private NotifyRequestDelete(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotifyRequestDelete() {
      ipAdd_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NotifyRequestDelete();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyRequestDelete(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idDelete_ = input.readInt32();
              break;
            }
            case 16: {

              idAdd_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAdd_ = s;
              break;
            }
            case 32: {

              listeningPortAdd_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.Builder.class);
    }

    public static final int ID_DELETE_FIELD_NUMBER = 1;
    private int idDelete_;
    /**
     * <code>int32 id_delete = 1;</code>
     * @return The idDelete.
     */
    @java.lang.Override
    public int getIdDelete() {
      return idDelete_;
    }

    public static final int ID_ADD_FIELD_NUMBER = 2;
    private int idAdd_;
    /**
     * <code>int32 id_add = 2;</code>
     * @return The idAdd.
     */
    @java.lang.Override
    public int getIdAdd() {
      return idAdd_;
    }

    public static final int IP_ADD_FIELD_NUMBER = 3;
    private volatile java.lang.Object ipAdd_;
    /**
     * <code>string ip_add = 3;</code>
     * @return The ipAdd.
     */
    @java.lang.Override
    public java.lang.String getIpAdd() {
      java.lang.Object ref = ipAdd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAdd_ = s;
        return s;
      }
    }
    /**
     * <code>string ip_add = 3;</code>
     * @return The bytes for ipAdd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpAddBytes() {
      java.lang.Object ref = ipAdd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAdd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LISTENINGPORT_ADD_FIELD_NUMBER = 4;
    private int listeningPortAdd_;
    /**
     * <code>int32 listeningPort_add = 4;</code>
     * @return The listeningPortAdd.
     */
    @java.lang.Override
    public int getListeningPortAdd() {
      return listeningPortAdd_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idDelete_ != 0) {
        output.writeInt32(1, idDelete_);
      }
      if (idAdd_ != 0) {
        output.writeInt32(2, idAdd_);
      }
      if (!getIpAddBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ipAdd_);
      }
      if (listeningPortAdd_ != 0) {
        output.writeInt32(4, listeningPortAdd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idDelete_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idDelete_);
      }
      if (idAdd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, idAdd_);
      }
      if (!getIpAddBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ipAdd_);
      }
      if (listeningPortAdd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, listeningPortAdd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete)) {
        return super.equals(obj);
      }
      it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete other = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete) obj;

      if (getIdDelete()
          != other.getIdDelete()) return false;
      if (getIdAdd()
          != other.getIdAdd()) return false;
      if (!getIpAdd()
          .equals(other.getIpAdd())) return false;
      if (getListeningPortAdd()
          != other.getListeningPortAdd()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_DELETE_FIELD_NUMBER;
      hash = (53 * hash) + getIdDelete();
      hash = (37 * hash) + ID_ADD_FIELD_NUMBER;
      hash = (53 * hash) + getIdAdd();
      hash = (37 * hash) + IP_ADD_FIELD_NUMBER;
      hash = (53 * hash) + getIpAdd().hashCode();
      hash = (37 * hash) + LISTENINGPORT_ADD_FIELD_NUMBER;
      hash = (53 * hash) + getListeningPortAdd();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyRequestDelete}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.maurosaladino.sdp.Proto.NotifyRequestDelete)
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDeleteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.Builder.class);
      }

      // Construct using it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idDelete_ = 0;

        idAdd_ = 0;

        ipAdd_ = "";

        listeningPortAdd_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete getDefaultInstanceForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.getDefaultInstance();
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete build() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete buildPartial() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete result = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete(this);
        result.idDelete_ = idDelete_;
        result.idAdd_ = idAdd_;
        result.ipAdd_ = ipAdd_;
        result.listeningPortAdd_ = listeningPortAdd_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete) {
          return mergeFrom((it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete other) {
        if (other == it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete.getDefaultInstance()) return this;
        if (other.getIdDelete() != 0) {
          setIdDelete(other.getIdDelete());
        }
        if (other.getIdAdd() != 0) {
          setIdAdd(other.getIdAdd());
        }
        if (!other.getIpAdd().isEmpty()) {
          ipAdd_ = other.ipAdd_;
          onChanged();
        }
        if (other.getListeningPortAdd() != 0) {
          setListeningPortAdd(other.getListeningPortAdd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idDelete_ ;
      /**
       * <code>int32 id_delete = 1;</code>
       * @return The idDelete.
       */
      @java.lang.Override
      public int getIdDelete() {
        return idDelete_;
      }
      /**
       * <code>int32 id_delete = 1;</code>
       * @param value The idDelete to set.
       * @return This builder for chaining.
       */
      public Builder setIdDelete(int value) {
        
        idDelete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id_delete = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdDelete() {
        
        idDelete_ = 0;
        onChanged();
        return this;
      }

      private int idAdd_ ;
      /**
       * <code>int32 id_add = 2;</code>
       * @return The idAdd.
       */
      @java.lang.Override
      public int getIdAdd() {
        return idAdd_;
      }
      /**
       * <code>int32 id_add = 2;</code>
       * @param value The idAdd to set.
       * @return This builder for chaining.
       */
      public Builder setIdAdd(int value) {
        
        idAdd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id_add = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdAdd() {
        
        idAdd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ipAdd_ = "";
      /**
       * <code>string ip_add = 3;</code>
       * @return The ipAdd.
       */
      public java.lang.String getIpAdd() {
        java.lang.Object ref = ipAdd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAdd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip_add = 3;</code>
       * @return The bytes for ipAdd.
       */
      public com.google.protobuf.ByteString
          getIpAddBytes() {
        java.lang.Object ref = ipAdd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAdd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip_add = 3;</code>
       * @param value The ipAdd to set.
       * @return This builder for chaining.
       */
      public Builder setIpAdd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAdd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip_add = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAdd() {
        
        ipAdd_ = getDefaultInstance().getIpAdd();
        onChanged();
        return this;
      }
      /**
       * <code>string ip_add = 3;</code>
       * @param value The bytes for ipAdd to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAdd_ = value;
        onChanged();
        return this;
      }

      private int listeningPortAdd_ ;
      /**
       * <code>int32 listeningPort_add = 4;</code>
       * @return The listeningPortAdd.
       */
      @java.lang.Override
      public int getListeningPortAdd() {
        return listeningPortAdd_;
      }
      /**
       * <code>int32 listeningPort_add = 4;</code>
       * @param value The listeningPortAdd to set.
       * @return This builder for chaining.
       */
      public Builder setListeningPortAdd(int value) {
        
        listeningPortAdd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 listeningPort_add = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearListeningPortAdd() {
        
        listeningPortAdd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.maurosaladino.sdp.Proto.NotifyRequestDelete)
    }

    // @@protoc_insertion_point(class_scope:it.maurosaladino.sdp.Proto.NotifyRequestDelete)
    private static final it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete();
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyRequestDelete>
        PARSER = new com.google.protobuf.AbstractParser<NotifyRequestDelete>() {
      @java.lang.Override
      public NotifyRequestDelete parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyRequestDelete(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotifyRequestDelete> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyRequestDelete> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyRequestDelete getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NotifyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.maurosaladino.sdp.Proto.NotifyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
     * @return The status.
     */
    it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status getStatus();
  }
  /**
   * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyResponse}
   */
  public static final class NotifyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.maurosaladino.sdp.Proto.NotifyResponse)
      NotifyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NotifyResponse.newBuilder() to construct.
    private NotifyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotifyResponse() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NotifyResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code it.maurosaladino.sdp.Proto.NotifyResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return OK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:it.maurosaladino.sdp.Proto.NotifyResponse.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status result = it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.valueOf(status_);
      return result == null ? it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.OK.getNumber()) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse)) {
        return super.equals(obj);
      }
      it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse other = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse) obj;

      if (status_ != other.status_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.maurosaladino.sdp.Proto.NotifyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.maurosaladino.sdp.Proto.NotifyResponse)
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.class, it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Builder.class);
      }

      // Construct using it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse getDefaultInstanceForType() {
        return it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse build() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse buildPartial() {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse result = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse) {
          return mergeFrom((it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse other) {
        if (other == it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status getStatus() {
        @SuppressWarnings("deprecation")
        it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status result = it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.valueOf(status_);
        return result == null ? it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.it.maurosaladino.sdp.Proto.NotifyResponse.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.maurosaladino.sdp.Proto.NotifyResponse)
    }

    // @@protoc_insertion_point(class_scope:it.maurosaladino.sdp.Proto.NotifyResponse)
    private static final it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse();
    }

    public static it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyResponse>
        PARSER = new com.google.protobuf.AbstractParser<NotifyResponse>() {
      @java.lang.Override
      public NotifyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotifyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotifyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.maurosaladino.sdp.Proto.P2PServiceOuterClass.NotifyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020P2PService.proto\022\032it.maurosaladino.sdp" +
      ".Proto\">\n\rNotifyRequest\022\n\n\002id\030\001 \001(\005\022\n\n\002i" +
      "p\030\002 \001(\t\022\025\n\rlisteningPort\030\003 \001(\005\"c\n\023Notify" +
      "RequestDelete\022\021\n\tid_delete\030\001 \001(\005\022\016\n\006id_a" +
      "dd\030\002 \001(\005\022\016\n\006ip_add\030\003 \001(\t\022\031\n\021listeningPor" +
      "t_add\030\004 \001(\005\"e\n\016NotifyResponse\022A\n\006status\030" +
      "\001 \001(\01621.it.maurosaladino.sdp.Proto.Notif" +
      "yResponse.Status\"\020\n\006Status\022\006\n\002OK\020\0002\300\003\n\nP" +
      "2PService\022c\n\nnotifyNext\022).it.maurosaladi" +
      "no.sdp.Proto.NotifyRequest\032*.it.maurosal" +
      "adino.sdp.Proto.NotifyResponse\022g\n\016notify" +
      "Previous\022).it.maurosaladino.sdp.Proto.No" +
      "tifyRequest\032*.it.maurosaladino.sdp.Proto" +
      ".NotifyResponse\022o\n\020notifyNextDelete\022/.it" +
      ".maurosaladino.sdp.Proto.NotifyRequestDe" +
      "lete\032*.it.maurosaladino.sdp.Proto.Notify" +
      "Response\022s\n\024notifyPreviousDelete\022/.it.ma" +
      "urosaladino.sdp.Proto.NotifyRequestDelet" +
      "e\032*.it.maurosaladino.sdp.Proto.NotifyRes" +
      "ponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_maurosaladino_sdp_Proto_NotifyRequest_descriptor,
        new java.lang.String[] { "Id", "Ip", "ListeningPort", });
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_maurosaladino_sdp_Proto_NotifyRequestDelete_descriptor,
        new java.lang.String[] { "IdDelete", "IdAdd", "IpAdd", "ListeningPortAdd", });
    internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_maurosaladino_sdp_Proto_NotifyResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
